name: carg
description: Get coinched ! Mobile app to save your card games

version: 0.10.4

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  cloud_firestore: ^0.16.0
  cupertino_icons: ^1.0.0
  enum_to_string: ^1.0.9
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.5.0
  flutter_spinkit: ^4.1.2+1
  flutter_svg: ^0.19.0
  font_awesome_flutter: ^8.8.1
  http: ^0.12.0+4
  intl: ^0.16.1
  package_info: ^0.4.1
  pedantic: ^1.8.0
  provider: ^4.1.2
  url_launcher: ^5.5.3
  syncfusion_flutter_charts: ^18.4.44+1
  syncfusion_flutter_gauges: ^18.4.44

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.2


flutter:
  uses-material-design: true

  fonts:
    - family: Josefin
      fonts:
        - asset: assets/fonts/Josefin_Sans/JosefinSans-Regular.ttf
        - asset: assets/fonts/Josefin_Sans/JosefinSans-Bold.ttf

  assets:
    - assets/images/card_game.svg
    - assets/images/search_by_algolia.svg
    - assets/config/
    - CHANGELOG.md

flutter_icons:
  ios: true
  android: true
  image_path_ios: assets/images/card_game_icon.png
  image_path_android: assets/images/card_game_icon.png

module:
  androidX: true
