name: carg
description: A new way to count points

version: 0.4.8

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_database: ^3.1.6
  cloud_firestore: ^0.13.7
  font_awesome_flutter: ^8.8.1
  package_info: ^0.4.1
  flutter_spinkit: ^4.1.2+1
  flutter_svg: ^0.18.1
  flutter_launcher_icons: ^0.7.5
  http: ^0.12.0+4
  intl: ^0.16.1
  enum_to_string: ^1.0.9
  pedantic: ^1.8.0
  provider: ^4.1.2
  shared_preferences: ^0.5.8
  algolia: ^0.1.7
  url_launcher: ^5.5.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Josefin
      fonts:
        - asset: assets/fonts/Josefin_Sans/JosefinSans-Regular.ttf
        - asset: assets/fonts/Josefin_Sans/JosefinSans-Bold.ttf

  assets:
    - assets/images/card_game.svg
    - assets/config/

flutter_icons:
  ios: true
  android: true
  image_path_ios: assets/images/card_game_icon.png
  image_path_android: assets/images/card_game_icon.png
