name: carg
description: Get coinched ! Mobile app to save your card games
publish_to: none

version: 1.8.0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '3.3.9'

dependencies:
  cloud_firestore: ^4.0.0
  firebase_core_platform_interface: ^4.4.0
  firebase_crashlytics: ^3.0.0
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  firebase_dynamic_links: ^5.0.0
  firebase_app_check: ^0.2.0
  google_sign_in: ^6.0.0
  google_mobile_ads: ^2.3.0
  cupertino_icons: ^1.0.2
  enum_to_string: ^2.0.1
  flutter_markdown: ^0.6.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^2.0.0
  flutter_secure_storage: ^7.0.0
  flutter_libphonenumber: ^1.3.0
  font_awesome_flutter: ^10.0.0
  http: ^0.13.0
  intl: ^0.17.0
  in_app_purchase: ^3.0.7
  package_info_plus : ^3.0.2
  provider: ^6.0.0
  url_launcher: ^6.0.2
  syncfusion_flutter_charts: ^20.1.57
  syncfusion_flutter_gauges: ^20.1.57
  infinite_scroll_pagination: ^3.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pin_code_fields: ^7.2.0
  collection: ^1.15.0
  crypto: ^3.0.2
  markdown: ^7.0.0
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1


dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  network_image_mock: ^2.0.1
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Josefin
      fonts:
        - asset: assets/fonts/Josefin_Sans/JosefinSans-Regular.ttf
        - asset: assets/fonts/Josefin_Sans/JosefinSans-Bold.ttf

  assets:
    - assets/images/card_game.svg
    - assets/images/algolia_logo.png
    - assets/images/google_logo.svg
    - assets/config/
    - assets/rules/
    - CHANGELOG.md

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: assets/images/card_game_icon.png
  image_path_android: assets/images/card_game_icon.png

module:
  androidX: true
