name: carg
description: Get coinched ! Mobile app to save your card games

version: 0.13.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^1.0.0
  firebase_crashlytics: ^2.0.2
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  firebase_auth_web: ^1.0.0
  google_sign_in: ^5.0.1
  cupertino_icons: ^1.0.2
  enum_to_string: ^2.0.1
  flutter_markdown: ^0.6.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.0.0-nullsafety
  http: ^0.13.0
  intl: ^0.17.0
  package_info: ^2.0.0
  pedantic: ^1.11.0
  provider: ^5.0.0
  url_launcher: ^6.0.2
  syncfusion_flutter_charts: ^19.1.54+1
  syncfusion_flutter_gauges: ^19.1.54+1
  infinite_scroll_pagination: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: Josefin
      fonts:
        - asset: assets/fonts/Josefin_Sans/JosefinSans-Regular.ttf
        - asset: assets/fonts/Josefin_Sans/JosefinSans-Bold.ttf

  assets:
    - assets/images/card_game.svg
    - assets/images/search_by_algolia.svg
    - assets/images/google_logo.svg
    - assets/config/
    - assets/rules/
    - CHANGELOG.md

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: assets/images/card_game_icon.png
  image_path_android: assets/images/card_game_icon.png

module:
  androidX: true
