name: Flutter - CI (build)
on:
  push:
    branches:
      - master
jobs:
  analyze:
    name: 'Analyze'
    runs-on: self-hosted
    container: devosud/flutter:latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Analyze code'
        run: flutter analyze
  test:
    name: 'Test'
    runs-on: self-hosted
    container: devosud/flutter:latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Analyze code'
        run: flutter test
  build_android:
    needs: [ analyze, test ]
    name: 'Build Android'
    runs-on: self-hosted
    container: devosud/flutter:latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Decrypt secret configuration'
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE: ${{secrets.PASSPHRASE}}
      - name: 'Build APK'
        run: flutter build apk --split-per-abi
        shell: 'bash'
      - name: 'Save APK'
        uses: actions/upload-artifact@v2
        with:
          name: 'apk-build'
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk