name: Flutter - CI (build)
on:
  push:
    branches:
      - master

jobs:
  analyze:
    name: 'Analyze'
    runs-on: ubuntu-latest
    container: devosud/flutter:latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Analyze code'
        run: flutter analyze
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    container: devosud/flutter:latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Test code'
        run: flutter test --coverage
      - name: 'Upload coverage report'
        uses: codecov/codecov-action@v1.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
  build_android:
    needs: [ analyze, test ]
    name: 'Build Android'
    runs-on: ubuntu-latest
    container: devosud/flutter:latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Decrypt secret configuration'
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE: ${{secrets.PASSPHRASE}}
      - name: 'Build APK'
        run: flutter build apk --split-per-abi --dart-define=FLAVOR=dev
        shell: 'bash'
      - name: 'Save APK'
        uses: actions/upload-artifact@v2
        with:
          name: 'apk-build'
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk