name: Firebase deploy hosted websites

on:
  push:
    paths:
      - 'firebase_hosting/**'

jobs:
  build_deploy:
    name: 'Build and deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
      - name: 'Setup Node / NPM'
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm install -g firebase-tools
      - name: 'Deploy hosting'
        run: |
          cd ./firebase_hosting
          firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}