name: Main workflow

on:
  push:
    branches:
      - main

jobs:
  flutter-test-analyze:
    uses: vareversat/carg/.github/workflows/flutter.analyze-test.action.yaml@main
    with:
      flutter_version: '2.8.1'
  functions:
    uses: vareversat/carg/.github/workflows/functions.action.yaml@main
  flutter-build:
    needs: [flutter-test-analyze]
    uses: vareversat/carg/.github/workflows/flutter.build.action.yaml@main
    with:
      flutter_version: '2.8.1'
      kind: 'abb'
  fastlane:
    needs: [flutter-build]
    uses: vareversat/carg/.github/workflows/fastlane.action.yaml@main
    with:
      lane: 'production'